# Generated by Django 5.2 on 2025-05-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_carrito_usuario_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='sinemail@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_receptor',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
